/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBotsRouteImport } from './routes/_authenticated/bots'
import { Route as AuthenticatedPainelRouteRouteImport } from './routes/_authenticated/painel/route'
import { Route as AuthenticatedBotRouteRouteImport } from './routes/_authenticated/$bot/route'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated/painel/perfil'
import { Route as AuthenticatedPainelDashboardRouteImport } from './routes/_authenticated/painel/dashboard'
import { Route as AuthenticatedPainelConfigRouteImport } from './routes/_authenticated/painel/config'
import { Route as AuthenticatedPainelBotsRouteImport } from './routes/_authenticated/painel/bots'
import { Route as AuthenticatedBotUsuariosRouteImport } from './routes/_authenticated/$bot/usuarios'
import { Route as AuthenticatedBotPlanosRouteImport } from './routes/_authenticated/$bot/planos'
import { Route as AuthenticatedBotPedidosRouteImport } from './routes/_authenticated/$bot/pedidos'
import { Route as AuthenticatedBotPagamentosRouteImport } from './routes/_authenticated/$bot/pagamentos'
import { Route as AuthenticatedBotOfertasRouteImport } from './routes/_authenticated/$bot/ofertas'
import { Route as AuthenticatedBotMensagensRouteImport } from './routes/_authenticated/$bot/mensagens'
import { Route as AuthenticatedBotGruposRouteImport } from './routes/_authenticated/$bot/grupos'
import { Route as AuthenticatedBotEstatisticasRouteImport } from './routes/_authenticated/$bot/estatisticas'
import { Route as AuthenticatedBotDashboardRouteImport } from './routes/_authenticated/$bot/dashboard'
import { Route as AuthenticatedBotConfiguracoesRouteImport } from './routes/_authenticated/$bot/configuracoes'
import { Route as AuthenticatedBotClientesRouteImport } from './routes/_authenticated/$bot/clientes'
import { Route as AuthenticatedBotAdministracaoRouteImport } from './routes/_authenticated/$bot/administracao'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramImageWebhookRouteImport } from './routes/api/public/telegram/image-webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as ApiPublicBroadcastsRunRouteImport } from './routes/api/public/broadcasts/run'
import { Route as ApiAdminImageBotMediaIdRouteImport } from './routes/api/admin/image-bot-media/$id'
import { Route as AuthenticatedPainelBotsNovoBotRouteImport } from './routes/_authenticated/painel/bots/novo-bot'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBotsRoute = AuthenticatedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRouteRoute =
  AuthenticatedPainelRouteRouteImport.update({
    id: '/painel',
    path: '/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotRouteRoute = AuthenticatedBotRouteRouteImport.update({
  id: '/$bot',
  path: '/$bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelDashboardRoute =
  AuthenticatedPainelDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelConfigRoute =
  AuthenticatedPainelConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelBotsRoute = AuthenticatedPainelBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedPainelRouteRoute,
} as any)
const AuthenticatedBotUsuariosRoute =
  AuthenticatedBotUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotPlanosRoute = AuthenticatedBotPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedBotRouteRoute,
} as any)
const AuthenticatedBotPedidosRoute = AuthenticatedBotPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedBotRouteRoute,
} as any)
const AuthenticatedBotPagamentosRoute =
  AuthenticatedBotPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotOfertasRoute = AuthenticatedBotOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedBotRouteRoute,
} as any)
const AuthenticatedBotMensagensRoute =
  AuthenticatedBotMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotGruposRoute = AuthenticatedBotGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedBotRouteRoute,
} as any)
const AuthenticatedBotEstatisticasRoute =
  AuthenticatedBotEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotDashboardRoute =
  AuthenticatedBotDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotConfiguracoesRoute =
  AuthenticatedBotConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotClientesRoute =
  AuthenticatedBotClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const AuthenticatedBotAdministracaoRoute =
  AuthenticatedBotAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedBotRouteRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramImageWebhookRoute =
  ApiPublicTelegramImageWebhookRouteImport.update({
    id: '/api/public/telegram/image-webhook',
    path: '/api/public/telegram/image-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBroadcastsRunRoute = ApiPublicBroadcastsRunRouteImport.update({
  id: '/api/public/broadcasts/run',
  path: '/api/public/broadcasts/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImageBotMediaIdRoute = ApiAdminImageBotMediaIdRouteImport.update({
  id: '/api/admin/image-bot-media/$id',
  path: '/api/admin/image-bot-media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelBotsNovoBotRoute =
  AuthenticatedPainelBotsNovoBotRouteImport.update({
    id: '/novo-bot',
    path: '/novo-bot',
    getParentRoute: () => AuthenticatedPainelBotsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagamento': typeof PagamentoRoute
  '/termos': typeof TermosRoute
  '/$bot': typeof AuthenticatedBotRouteRouteWithChildren
  '/painel': typeof AuthenticatedPainelRouteRouteWithChildren
  '/bots': typeof AuthenticatedBotsRoute
  '/$bot/administracao': typeof AuthenticatedBotAdministracaoRoute
  '/$bot/clientes': typeof AuthenticatedBotClientesRoute
  '/$bot/configuracoes': typeof AuthenticatedBotConfiguracoesRoute
  '/$bot/dashboard': typeof AuthenticatedBotDashboardRoute
  '/$bot/estatisticas': typeof AuthenticatedBotEstatisticasRoute
  '/$bot/grupos': typeof AuthenticatedBotGruposRoute
  '/$bot/mensagens': typeof AuthenticatedBotMensagensRoute
  '/$bot/ofertas': typeof AuthenticatedBotOfertasRoute
  '/$bot/pagamentos': typeof AuthenticatedBotPagamentosRoute
  '/$bot/pedidos': typeof AuthenticatedBotPedidosRoute
  '/$bot/planos': typeof AuthenticatedBotPlanosRoute
  '/$bot/usuarios': typeof AuthenticatedBotUsuariosRoute
  '/painel/bots': typeof AuthenticatedPainelBotsRouteWithChildren
  '/painel/config': typeof AuthenticatedPainelConfigRoute
  '/painel/dashboard': typeof AuthenticatedPainelDashboardRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/painel/bots/novo-bot': typeof AuthenticatedPainelBotsNovoBotRoute
  '/api/admin/image-bot-media/$id': typeof ApiAdminImageBotMediaIdRoute
  '/api/public/broadcasts/run': typeof ApiPublicBroadcastsRunRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/image-webhook': typeof ApiPublicTelegramImageWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagamento': typeof PagamentoRoute
  '/termos': typeof TermosRoute
  '/$bot': typeof AuthenticatedBotRouteRouteWithChildren
  '/painel': typeof AuthenticatedPainelRouteRouteWithChildren
  '/bots': typeof AuthenticatedBotsRoute
  '/$bot/administracao': typeof AuthenticatedBotAdministracaoRoute
  '/$bot/clientes': typeof AuthenticatedBotClientesRoute
  '/$bot/configuracoes': typeof AuthenticatedBotConfiguracoesRoute
  '/$bot/dashboard': typeof AuthenticatedBotDashboardRoute
  '/$bot/estatisticas': typeof AuthenticatedBotEstatisticasRoute
  '/$bot/grupos': typeof AuthenticatedBotGruposRoute
  '/$bot/mensagens': typeof AuthenticatedBotMensagensRoute
  '/$bot/ofertas': typeof AuthenticatedBotOfertasRoute
  '/$bot/pagamentos': typeof AuthenticatedBotPagamentosRoute
  '/$bot/pedidos': typeof AuthenticatedBotPedidosRoute
  '/$bot/planos': typeof AuthenticatedBotPlanosRoute
  '/$bot/usuarios': typeof AuthenticatedBotUsuariosRoute
  '/painel/bots': typeof AuthenticatedPainelBotsRouteWithChildren
  '/painel/config': typeof AuthenticatedPainelConfigRoute
  '/painel/dashboard': typeof AuthenticatedPainelDashboardRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/painel/bots/novo-bot': typeof AuthenticatedPainelBotsNovoBotRoute
  '/api/admin/image-bot-media/$id': typeof ApiAdminImageBotMediaIdRoute
  '/api/public/broadcasts/run': typeof ApiPublicBroadcastsRunRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/image-webhook': typeof ApiPublicTelegramImageWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/pagamento': typeof PagamentoRoute
  '/termos': typeof TermosRoute
  '/_authenticated/$bot': typeof AuthenticatedBotRouteRouteWithChildren
  '/_authenticated/painel': typeof AuthenticatedPainelRouteRouteWithChildren
  '/_authenticated/bots': typeof AuthenticatedBotsRoute
  '/_authenticated/$bot/administracao': typeof AuthenticatedBotAdministracaoRoute
  '/_authenticated/$bot/clientes': typeof AuthenticatedBotClientesRoute
  '/_authenticated/$bot/configuracoes': typeof AuthenticatedBotConfiguracoesRoute
  '/_authenticated/$bot/dashboard': typeof AuthenticatedBotDashboardRoute
  '/_authenticated/$bot/estatisticas': typeof AuthenticatedBotEstatisticasRoute
  '/_authenticated/$bot/grupos': typeof AuthenticatedBotGruposRoute
  '/_authenticated/$bot/mensagens': typeof AuthenticatedBotMensagensRoute
  '/_authenticated/$bot/ofertas': typeof AuthenticatedBotOfertasRoute
  '/_authenticated/$bot/pagamentos': typeof AuthenticatedBotPagamentosRoute
  '/_authenticated/$bot/pedidos': typeof AuthenticatedBotPedidosRoute
  '/_authenticated/$bot/planos': typeof AuthenticatedBotPlanosRoute
  '/_authenticated/$bot/usuarios': typeof AuthenticatedBotUsuariosRoute
  '/_authenticated/painel/bots': typeof AuthenticatedPainelBotsRouteWithChildren
  '/_authenticated/painel/config': typeof AuthenticatedPainelConfigRoute
  '/_authenticated/painel/dashboard': typeof AuthenticatedPainelDashboardRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/_authenticated/painel/bots/novo-bot': typeof AuthenticatedPainelBotsNovoBotRoute
  '/api/admin/image-bot-media/$id': typeof ApiAdminImageBotMediaIdRoute
  '/api/public/broadcasts/run': typeof ApiPublicBroadcastsRunRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/image-webhook': typeof ApiPublicTelegramImageWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pagamento'
    | '/termos'
    | '/$bot'
    | '/painel'
    | '/bots'
    | '/$bot/administracao'
    | '/$bot/clientes'
    | '/$bot/configuracoes'
    | '/$bot/dashboard'
    | '/$bot/estatisticas'
    | '/$bot/grupos'
    | '/$bot/mensagens'
    | '/$bot/ofertas'
    | '/$bot/pagamentos'
    | '/$bot/pedidos'
    | '/$bot/planos'
    | '/$bot/usuarios'
    | '/painel/bots'
    | '/painel/config'
    | '/painel/dashboard'
    | '/painel/perfil'
    | '/painel/bots/novo-bot'
    | '/api/admin/image-bot-media/$id'
    | '/api/public/broadcasts/run'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/image-webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pagamento'
    | '/termos'
    | '/$bot'
    | '/painel'
    | '/bots'
    | '/$bot/administracao'
    | '/$bot/clientes'
    | '/$bot/configuracoes'
    | '/$bot/dashboard'
    | '/$bot/estatisticas'
    | '/$bot/grupos'
    | '/$bot/mensagens'
    | '/$bot/ofertas'
    | '/$bot/pagamentos'
    | '/$bot/pedidos'
    | '/$bot/planos'
    | '/$bot/usuarios'
    | '/painel/bots'
    | '/painel/config'
    | '/painel/dashboard'
    | '/painel/perfil'
    | '/painel/bots/novo-bot'
    | '/api/admin/image-bot-media/$id'
    | '/api/public/broadcasts/run'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/image-webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/pagamento'
    | '/termos'
    | '/_authenticated/$bot'
    | '/_authenticated/painel'
    | '/_authenticated/bots'
    | '/_authenticated/$bot/administracao'
    | '/_authenticated/$bot/clientes'
    | '/_authenticated/$bot/configuracoes'
    | '/_authenticated/$bot/dashboard'
    | '/_authenticated/$bot/estatisticas'
    | '/_authenticated/$bot/grupos'
    | '/_authenticated/$bot/mensagens'
    | '/_authenticated/$bot/ofertas'
    | '/_authenticated/$bot/pagamentos'
    | '/_authenticated/$bot/pedidos'
    | '/_authenticated/$bot/planos'
    | '/_authenticated/$bot/usuarios'
    | '/_authenticated/painel/bots'
    | '/_authenticated/painel/config'
    | '/_authenticated/painel/dashboard'
    | '/_authenticated/painel/perfil'
    | '/_authenticated/painel/bots/novo-bot'
    | '/api/admin/image-bot-media/$id'
    | '/api/public/broadcasts/run'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/image-webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PagamentoRoute: typeof PagamentoRoute
  TermosRoute: typeof TermosRoute
  ApiAdminImageBotMediaIdRoute: typeof ApiAdminImageBotMediaIdRoute
  ApiPublicBroadcastsRunRoute: typeof ApiPublicBroadcastsRunRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTelegramImageWebhookRoute: typeof ApiPublicTelegramImageWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bots': {
      id: '/_authenticated/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedBotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$bot': {
      id: '/_authenticated/$bot'
      path: '/$bot'
      fullPath: '/$bot'
      preLoaderRoute: typeof AuthenticatedBotRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/dashboard': {
      id: '/_authenticated/painel/dashboard'
      path: '/dashboard'
      fullPath: '/painel/dashboard'
      preLoaderRoute: typeof AuthenticatedPainelDashboardRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/config': {
      id: '/_authenticated/painel/config'
      path: '/config'
      fullPath: '/painel/config'
      preLoaderRoute: typeof AuthenticatedPainelConfigRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/bots': {
      id: '/_authenticated/painel/bots'
      path: '/bots'
      fullPath: '/painel/bots'
      preLoaderRoute: typeof AuthenticatedPainelBotsRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/$bot/usuarios': {
      id: '/_authenticated/$bot/usuarios'
      path: '/usuarios'
      fullPath: '/$bot/usuarios'
      preLoaderRoute: typeof AuthenticatedBotUsuariosRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/planos': {
      id: '/_authenticated/$bot/planos'
      path: '/planos'
      fullPath: '/$bot/planos'
      preLoaderRoute: typeof AuthenticatedBotPlanosRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/pedidos': {
      id: '/_authenticated/$bot/pedidos'
      path: '/pedidos'
      fullPath: '/$bot/pedidos'
      preLoaderRoute: typeof AuthenticatedBotPedidosRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/pagamentos': {
      id: '/_authenticated/$bot/pagamentos'
      path: '/pagamentos'
      fullPath: '/$bot/pagamentos'
      preLoaderRoute: typeof AuthenticatedBotPagamentosRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/ofertas': {
      id: '/_authenticated/$bot/ofertas'
      path: '/ofertas'
      fullPath: '/$bot/ofertas'
      preLoaderRoute: typeof AuthenticatedBotOfertasRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/mensagens': {
      id: '/_authenticated/$bot/mensagens'
      path: '/mensagens'
      fullPath: '/$bot/mensagens'
      preLoaderRoute: typeof AuthenticatedBotMensagensRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/grupos': {
      id: '/_authenticated/$bot/grupos'
      path: '/grupos'
      fullPath: '/$bot/grupos'
      preLoaderRoute: typeof AuthenticatedBotGruposRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/estatisticas': {
      id: '/_authenticated/$bot/estatisticas'
      path: '/estatisticas'
      fullPath: '/$bot/estatisticas'
      preLoaderRoute: typeof AuthenticatedBotEstatisticasRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/dashboard': {
      id: '/_authenticated/$bot/dashboard'
      path: '/dashboard'
      fullPath: '/$bot/dashboard'
      preLoaderRoute: typeof AuthenticatedBotDashboardRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/configuracoes': {
      id: '/_authenticated/$bot/configuracoes'
      path: '/configuracoes'
      fullPath: '/$bot/configuracoes'
      preLoaderRoute: typeof AuthenticatedBotConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/clientes': {
      id: '/_authenticated/$bot/clientes'
      path: '/clientes'
      fullPath: '/$bot/clientes'
      preLoaderRoute: typeof AuthenticatedBotClientesRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/_authenticated/$bot/administracao': {
      id: '/_authenticated/$bot/administracao'
      path: '/administracao'
      fullPath: '/$bot/administracao'
      preLoaderRoute: typeof AuthenticatedBotAdministracaoRouteImport
      parentRoute: typeof AuthenticatedBotRouteRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/image-webhook': {
      id: '/api/public/telegram/image-webhook'
      path: '/api/public/telegram/image-webhook'
      fullPath: '/api/public/telegram/image-webhook'
      preLoaderRoute: typeof ApiPublicTelegramImageWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/broadcasts/run': {
      id: '/api/public/broadcasts/run'
      path: '/api/public/broadcasts/run'
      fullPath: '/api/public/broadcasts/run'
      preLoaderRoute: typeof ApiPublicBroadcastsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/image-bot-media/$id': {
      id: '/api/admin/image-bot-media/$id'
      path: '/api/admin/image-bot-media/$id'
      fullPath: '/api/admin/image-bot-media/$id'
      preLoaderRoute: typeof ApiAdminImageBotMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/bots/novo-bot': {
      id: '/_authenticated/painel/bots/novo-bot'
      path: '/novo-bot'
      fullPath: '/painel/bots/novo-bot'
      preLoaderRoute: typeof AuthenticatedPainelBotsNovoBotRouteImport
      parentRoute: typeof AuthenticatedPainelBotsRoute
    }
  }
}

interface AuthenticatedBotRouteRouteChildren {
  AuthenticatedBotAdministracaoRoute: typeof AuthenticatedBotAdministracaoRoute
  AuthenticatedBotClientesRoute: typeof AuthenticatedBotClientesRoute
  AuthenticatedBotConfiguracoesRoute: typeof AuthenticatedBotConfiguracoesRoute
  AuthenticatedBotDashboardRoute: typeof AuthenticatedBotDashboardRoute
  AuthenticatedBotEstatisticasRoute: typeof AuthenticatedBotEstatisticasRoute
  AuthenticatedBotGruposRoute: typeof AuthenticatedBotGruposRoute
  AuthenticatedBotMensagensRoute: typeof AuthenticatedBotMensagensRoute
  AuthenticatedBotOfertasRoute: typeof AuthenticatedBotOfertasRoute
  AuthenticatedBotPagamentosRoute: typeof AuthenticatedBotPagamentosRoute
  AuthenticatedBotPedidosRoute: typeof AuthenticatedBotPedidosRoute
  AuthenticatedBotPlanosRoute: typeof AuthenticatedBotPlanosRoute
  AuthenticatedBotUsuariosRoute: typeof AuthenticatedBotUsuariosRoute
}

const AuthenticatedBotRouteRouteChildren: AuthenticatedBotRouteRouteChildren = {
  AuthenticatedBotAdministracaoRoute: AuthenticatedBotAdministracaoRoute,
  AuthenticatedBotClientesRoute: AuthenticatedBotClientesRoute,
  AuthenticatedBotConfiguracoesRoute: AuthenticatedBotConfiguracoesRoute,
  AuthenticatedBotDashboardRoute: AuthenticatedBotDashboardRoute,
  AuthenticatedBotEstatisticasRoute: AuthenticatedBotEstatisticasRoute,
  AuthenticatedBotGruposRoute: AuthenticatedBotGruposRoute,
  AuthenticatedBotMensagensRoute: AuthenticatedBotMensagensRoute,
  AuthenticatedBotOfertasRoute: AuthenticatedBotOfertasRoute,
  AuthenticatedBotPagamentosRoute: AuthenticatedBotPagamentosRoute,
  AuthenticatedBotPedidosRoute: AuthenticatedBotPedidosRoute,
  AuthenticatedBotPlanosRoute: AuthenticatedBotPlanosRoute,
  AuthenticatedBotUsuariosRoute: AuthenticatedBotUsuariosRoute,
}

const AuthenticatedBotRouteRouteWithChildren =
  AuthenticatedBotRouteRoute._addFileChildren(
    AuthenticatedBotRouteRouteChildren,
  )

interface AuthenticatedPainelBotsRouteChildren {
  AuthenticatedPainelBotsNovoBotRoute: typeof AuthenticatedPainelBotsNovoBotRoute
}

const AuthenticatedPainelBotsRouteChildren: AuthenticatedPainelBotsRouteChildren =
  {
    AuthenticatedPainelBotsNovoBotRoute: AuthenticatedPainelBotsNovoBotRoute,
  }

const AuthenticatedPainelBotsRouteWithChildren =
  AuthenticatedPainelBotsRoute._addFileChildren(
    AuthenticatedPainelBotsRouteChildren,
  )

interface AuthenticatedPainelRouteRouteChildren {
  AuthenticatedPainelBotsRoute: typeof AuthenticatedPainelBotsRouteWithChildren
  AuthenticatedPainelConfigRoute: typeof AuthenticatedPainelConfigRoute
  AuthenticatedPainelDashboardRoute: typeof AuthenticatedPainelDashboardRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute
}

const AuthenticatedPainelRouteRouteChildren: AuthenticatedPainelRouteRouteChildren =
  {
    AuthenticatedPainelBotsRoute: AuthenticatedPainelBotsRouteWithChildren,
    AuthenticatedPainelConfigRoute: AuthenticatedPainelConfigRoute,
    AuthenticatedPainelDashboardRoute: AuthenticatedPainelDashboardRoute,
    AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,
  }

const AuthenticatedPainelRouteRouteWithChildren =
  AuthenticatedPainelRouteRoute._addFileChildren(
    AuthenticatedPainelRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBotRouteRoute: typeof AuthenticatedBotRouteRouteWithChildren
  AuthenticatedPainelRouteRoute: typeof AuthenticatedPainelRouteRouteWithChildren
  AuthenticatedBotsRoute: typeof AuthenticatedBotsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBotRouteRoute: AuthenticatedBotRouteRouteWithChildren,
  AuthenticatedPainelRouteRoute: AuthenticatedPainelRouteRouteWithChildren,
  AuthenticatedBotsRoute: AuthenticatedBotsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PagamentoRoute: PagamentoRoute,
  TermosRoute: TermosRoute,
  ApiAdminImageBotMediaIdRoute: ApiAdminImageBotMediaIdRoute,
  ApiPublicBroadcastsRunRoute: ApiPublicBroadcastsRunRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTelegramImageWebhookRoute: ApiPublicTelegramImageWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
